module tb_rasterizer_100;
    reg clk, rst, start;
    reg [6:0] ax, ay, bx, by, cx, cy;
    wire pixel_valid, done;
    wire [5:0] pixel_x, pixel_y;
    integer pixel_count, test_num;
    rasterizer dut (
        .clk(clk), .rst(rst),
        .ax(ax), .ay(ay), .bx(bx), .by(by), .cx(cx), .cy(cy),
        .start(start), .pixel_valid(pixel_valid),
        .pixel_x(pixel_x), .pixel_y(pixel_y), .done(done));
    initial clk = 0;
    always #5 clk = ~clk;
    always @(posedge clk) begin
        if (pixel_valid) begin
            pixel_count = pixel_count + 1;
            $display("PIXEL_%0d (%0d, %0d)", test_num, pixel_x, pixel_y);
        end
    end
    task do_reset;
        begin
            rst=1; start=0;
            ax=0; ay=0; bx=0; by=0; cx=0; cy=0;
            repeat(3) @(posedge clk);
            rst=0; @(posedge clk);
        end
    endtask
    initial begin
        $dumpfile("tb_rasterizer_100.vcd");
        $dumpvars(0, tb_rasterizer_100);
        pixel_count = 0; test_num = 0;
        do_reset; pixel_count=0; test_num=1;
        ax=25; ay=8; bx=5; by=28; cx=13; cy=12;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_1_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=2;
        ax=12; ay=9; bx=28; by=8; cx=26; cy=28;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_2_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=3;
        ax=22; ay=7; bx=23; by=18; cx=6; cy=5;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_3_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=4;
        ax=7; ay=11; bx=12; by=21; cx=24; cy=5;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_4_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=5;
        ax=22; ay=11; bx=27; by=25; cx=27; cy=22;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_5_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=6;
        ax=18; ay=12; bx=19; by=23; cx=13; cy=30;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_6_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=7;
        ax=5; ay=29; bx=30; by=10; cx=27; cy=18;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_7_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=8;
        ax=15; ay=13; bx=9; by=11; cx=29; cy=15;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_8_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=9;
        ax=8; ay=7; bx=17; by=8; cx=16; cy=16;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_9_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=10;
        ax=24; ay=13; bx=30; by=6; cx=28; cy=19;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_10_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=11;
        ax=22; ay=8; bx=17; by=7; cx=22; cy=14;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_11_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=12;
        ax=25; ay=24; bx=16; by=23; cx=11; cy=27;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_12_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=13;
        ax=7; ay=6; bx=26; by=12; cx=29; cy=14;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_13_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=14;
        ax=7; ay=12; bx=8; by=17; cx=13; cy=19;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_14_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=15;
        ax=25; ay=16; bx=10; by=16; cx=16; cy=11;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_15_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=16;
        ax=26; ay=13; bx=27; by=26; cx=25; cy=7;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_16_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=17;
        ax=24; ay=25; bx=10; by=22; cx=28; cy=12;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_17_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=18;
        ax=10; ay=19; bx=17; by=13; cx=25; cy=27;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_18_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=19;
        ax=22; ay=12; bx=26; by=15; cx=29; cy=29;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_19_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=20;
        ax=6; ay=12; bx=6; by=30; cx=15; cy=17;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_20_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=21;
        ax=34; ay=8; bx=27; by=40; cx=27; cy=63;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_21_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=22;
        ax=50; ay=58; bx=18; by=33; cx=17; cy=31;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_22_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=23;
        ax=33; ay=54; bx=51; by=46; cx=28; cy=17;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_23_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=24;
        ax=63; ay=11; bx=6; by=14; cx=19; cy=20;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_24_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=25;
        ax=54; ay=8; bx=49; by=48; cx=59; cy=32;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_25_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=26;
        ax=1; ay=14; bx=34; by=43; cx=14; cy=37;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_26_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=27;
        ax=55; ay=20; bx=58; by=0; cx=33; cy=22;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_27_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=28;
        ax=13; ay=38; bx=25; by=19; cx=47; cy=20;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_28_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=29;
        ax=0; ay=41; bx=62; by=2; cx=14; cy=46;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_29_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=30;
        ax=39; ay=30; bx=7; by=30; cx=10; cy=10;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_30_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=31;
        ax=62; ay=8; bx=16; by=16; cx=60; cy=21;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_31_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=32;
        ax=33; ay=54; bx=27; by=25; cx=39; cy=51;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_32_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=33;
        ax=47; ay=56; bx=57; by=15; cx=31; cy=28;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_33_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=34;
        ax=8; ay=43; bx=2; by=29; cx=28; cy=0;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_34_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=35;
        ax=9; ay=7; bx=29; by=8; cx=4; cy=42;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_35_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=36;
        ax=9; ay=30; bx=35; by=62; cx=27; cy=16;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_36_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=37;
        ax=60; ay=31; bx=60; by=52; cx=24; cy=12;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_37_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=38;
        ax=12; ay=55; bx=45; by=54; cx=52; cy=59;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_38_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=39;
        ax=6; ay=12; bx=7; by=51; cx=43; cy=13;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_39_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=40;
        ax=31; ay=24; bx=24; by=57; cx=17; cy=54;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_40_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=41;
        ax=21; ay=13; bx=12; by=44; cx=57; cy=44;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_41_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=42;
        ax=14; ay=19; bx=22; by=55; cx=33; cy=55;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_42_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=43;
        ax=13; ay=5; bx=29; by=32; cx=57; cy=32;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_43_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=44;
        ax=25; ay=10; bx=20; by=43; cx=45; cy=43;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_44_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=45;
        ax=23; ay=17; bx=6; by=58; cx=35; cy=58;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_45_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=46;
        ax=34; ay=5; bx=13; by=42; cx=59; cy=42;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_46_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=47;
        ax=39; ay=14; bx=27; by=43; cx=60; cy=43;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_47_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=48;
        ax=45; ay=20; bx=11; by=34; cx=39; cy=34;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_48_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=49;
        ax=23; ay=6; bx=28; by=48; cx=47; cy=48;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_49_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=50;
        ax=13; ay=15; bx=6; by=31; cx=48; cy=31;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_50_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=51;
        ax=40; ay=10; bx=21; by=31; cx=32; cy=31;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_51_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=52;
        ax=21; ay=7; bx=7; by=49; cx=51; cy=49;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_52_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=53;
        ax=25; ay=17; bx=23; by=33; cx=37; cy=33;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_53_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=54;
        ax=47; ay=6; bx=7; by=49; cx=43; cy=49;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_54_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=55;
        ax=47; ay=15; bx=13; by=59; cx=36; cy=59;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_55_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=56;
        ax=30; ay=12; bx=17; by=38; cx=34; cy=38;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_56_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=57;
        ax=29; ay=19; bx=29; by=40; cx=59; cy=40;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_57_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=58;
        ax=14; ay=5; bx=24; by=44; cx=48; cy=44;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_58_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=59;
        ax=16; ay=7; bx=11; by=47; cx=46; cy=47;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_59_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=60;
        ax=26; ay=9; bx=16; by=59; cx=58; cy=59;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_60_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=61;
        ax=7; ay=12; bx=41; by=12; cx=28; cy=35;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_61_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=62;
        ax=19; ay=14; bx=49; by=14; cx=43; cy=30;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_62_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=63;
        ax=26; ay=14; bx=59; by=14; cx=16; cy=60;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_63_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=64;
        ax=9; ay=13; bx=33; by=13; cx=16; cy=53;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_64_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=65;
        ax=22; ay=9; bx=38; by=9; cx=28; cy=49;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_65_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=66;
        ax=11; ay=15; bx=36; by=15; cx=50; cy=57;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_66_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=67;
        ax=13; ay=20; bx=38; by=20; cx=13; cy=32;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_67_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=68;
        ax=25; ay=18; bx=56; by=18; cx=27; cy=31;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_68_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=69;
        ax=5; ay=15; bx=54; by=15; cx=18; cy=50;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_69_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=70;
        ax=13; ay=10; bx=53; by=10; cx=38; cy=47;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_70_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=71;
        ax=27; ay=18; bx=47; by=18; cx=10; cy=33;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_71_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=72;
        ax=7; ay=9; bx=47; by=9; cx=12; cy=56;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_72_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=73;
        ax=16; ay=9; bx=43; by=9; cx=18; cy=31;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_73_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=74;
        ax=14; ay=16; bx=58; by=16; cx=12; cy=58;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_74_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=75;
        ax=16; ay=11; bx=51; by=11; cx=25; cy=51;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_75_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=76;
        ax=8; ay=16; bx=54; by=16; cx=45; cy=58;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_76_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=77;
        ax=18; ay=9; bx=59; by=9; cx=25; cy=57;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_77_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=78;
        ax=10; ay=10; bx=58; by=10; cx=36; cy=30;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_78_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=79;
        ax=10; ay=15; bx=55; by=15; cx=36; cy=55;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_79_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=80;
        ax=26; ay=12; bx=38; by=12; cx=20; cy=55;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_80_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=81;
        ax=5; ay=5; bx=5; by=5; cx=5; cy=5;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_81_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=82;
        ax=10; ay=10; bx=10; by=10; cx=10; cy=10;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_82_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=83;
        ax=0; ay=0; bx=63; by=0; cx=0; cy=63;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_83_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=84;
        ax=0; ay=0; bx=63; by=63; cx=0; cy=63;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_84_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=85;
        ax=0; ay=0; bx=31; by=63; cx=63; cy=0;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_85_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=86;
        ax=48; ay=13; bx=4; by=13; cx=60; cy=28;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_86_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=87;
        ax=58; ay=25; bx=44; by=25; cx=39; cy=29;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_87_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=88;
        ax=3; ay=28; bx=24; by=28; cx=51; cy=42;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_88_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=89;
        ax=8; ay=35; bx=35; by=35; cx=44; cy=51;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_89_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=90;
        ax=3; ay=42; bx=14; by=42; cx=33; cy=22;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_90_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=91;
        ax=4; ay=33; bx=13; by=33; cx=55; cy=44;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_91_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=92;
        ax=55; ay=40; bx=14; by=40; cx=49; cy=24;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_92_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=93;
        ax=5; ay=32; bx=55; by=32; cx=0; cy=25;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_93_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=94;
        ax=55; ay=46; bx=8; by=46; cx=42; cy=40;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_94_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=95;
        ax=38; ay=15; bx=39; by=15; cx=52; cy=41;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_95_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=96;
        ax=37; ay=51; bx=16; by=51; cx=24; cy=53;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_96_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=97;
        ax=22; ay=48; bx=38; by=48; cx=51; cy=0;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_97_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=98;
        ax=36; ay=38; bx=26; by=38; cx=55; cy=41;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_98_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=99;
        ax=56; ay=59; bx=56; by=59; cx=27; cy=60;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_99_DONE pixels=%0d", pixel_count);
        do_reset; pixel_count=0; test_num=100;
        ax=10; ay=21; bx=36; by=21; cx=42; cy=11;
        @(posedge clk); start=1; @(posedge clk); start=0;
        wait(done===1'b1); @(posedge clk);
        $display("TEST_100_DONE pixels=%0d", pixel_count);
        $display("ALL_100_DONE");
        $finish;
    end
endmodule